# Generated by Django 5.0.5 on 2024-05-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('numero_pokedex', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=255)),
                ('generacion', models.IntegerField()),
                ('imagen', models.URLField(blank=True, max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('mejor_atributo', models.CharField(max_length=100)),
                ('descripcion_poke', models.CharField(max_length=100)),
                ('especie_poke', models.CharField(max_length=100)),
                ('habilidades_poke', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null='False', unique=True)),
                ('contrasena', models.CharField(max_length=128)),
            ],
        ),
    ]
