# Generated by Django 5.0.5 on 2024-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('numero_pokedex', models.IntegerField(unique=True)),
                ('tipo', models.CharField(max_length=255)),
                ('generacion', models.IntegerField()),
                ('imagen', models.URLField(blank=True, max_length=255)),
                ('hp', models.IntegerField()),
            ],
        ),
    ]
