# Generated by Django 5.0.5 on 2024-05-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='id',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='numero_pokedex',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
